name: Imagine Smith
favicon: null
layout_spectrum: 0.07879250543192029
typography_spectrum: 0.8308672567363828
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2595534445717931
  lightness: 0.02539949445053935
  saturation: 0.03527773288078606
  rhythmicContrast: 0.36900479276664555
purpose: []
